# $OpenBSD$

COMMENT=	Object-oriented filesystem paths

MODPY_EGG_VERSION=	2.2.1
DISTNAME=		pathlib2-${MODPY_EGG_VERSION}
PKGNAME=		py-pathlib2-${MODPY_EGG_VERSION}

HOMEPAGE=		https://github.com/mcmtroffaes/pathlib2

CATEGORIES=	devel

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_SETUPTOOLS=	Yes

RUN_DEPENDS=		devel/py-scandir \
			devel/py-six

.include <bsd.port.mk>
