# $OpenBSD$

COMMENT=	Azure CLI Namespace Package

MODPY_EGG_VERSION=	0.1.0b11
DISTNAME=		azure-cli-nspkg-${MODPY_EGG_VERSION}
PKGNAME=		py-azure-cli-nspkg-${MODPY_EGG_VERSION}

HOMEPAGE=		https://github.com/Azure/azure-cli

CATEGORIES=	devel

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_SETUPTOOLS=	Yes

.include <bsd.port.mk>
