#	$OpenBSD$

COMMENT=	Azure VHD utilities
CATEGORIES=	sysutils

GH_ACCOUNT=	Microsoft
GH_PROJECT=	azure-vhd-utils
GH_COMMIT=	2dd43d88c85c06c55828c86159d4583db9d41fbb
DISTNAME=	${GH_PROJECT}-20170104

# MIT
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB=	c pthread

MODULES=	lang/go

.include <bsd.port.mk>
