# $OpenBSD$

COMMENT=	Azure Service Bus Client Library for Python

MODPY_EGG_VERSION=	0.20.3
DISTNAME=		azure-servicebus-${MODPY_EGG_VERSION}
PKGNAME=		py-azure-servicebus-${MODPY_EGG_VERSION}
EXTRACT_SUFX=		.zip

HOMEPAGE=		https://github.com/Azure/azure-sdk-for-python

CATEGORIES=	devel

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_SETUPTOOLS=	Yes

.include <bsd.port.mk>
