# $OpenBSD$

COMMENT=	OAuthlib authentication support for Requests

MODPY_EGG_VERSION=	0.7.0
DISTNAME=		requests-oauthlib-${MODPY_EGG_VERSION}
PKGNAME=		py-requests-oauthlib-${MODPY_EGG_VERSION}

CATEGORIES=	www devel

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_SETUPTOOLS=	Yes

.include <bsd.port.mk>
