# $OpenBSD$

COMMENT=	Azure Storage Client Library

MODPY_EGG_VERSION=	0.33.0
DISTNAME=		azure-storage-${MODPY_EGG_VERSION}
PKGNAME=		py-azure-storage-${MODPY_EGG_VERSION}
EXTRACT_SUFX=		.zip

HOMEPAGE=		https://github.com/Azure/azure-sdk-for-python

CATEGORIES=	devel

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_SETUPTOOLS=	Yes

#RUN_DEPENDS=		devel/py-azure-cli-core

.include <bsd.port.mk>
