# $OpenBSD$

COMMENT=	Azure Legacy Service Management Client Library for Python

MODPY_EGG_VERSION=	0.20.6
DISTNAME=		azure-servicemanagement-legacy-${MODPY_EGG_VERSION}
PKGNAME=		py-azure-servicemanagement-legacy-${MODPY_EGG_VERSION}
EXTRACT_SUFX=		.zip

HOMEPAGE=		https://github.com/Azure/azure-sdk-for-python

CATEGORIES=	devel

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_SETUPTOOLS=	Yes

.include <bsd.port.mk>
