# $OpenBSD$

COMMENT=	Azure Storage Client Library multi API support

GH_ACCOUNT=	derekbekoe
GH_PROJECT=	azure-multiapi-storage-python
GH_COMMIT=	b0242f38e11a9962f7e7254459d168fa71d13983
V=		0.1.0
DISTNAME=	py-azure-multiapi-storage-${V}
PKGNAME=	py-azure-multiapi-storage-${V}

CATEGORIES=	devel

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/python

MODPY_SETUPTOOLS=	Yes

.include <bsd.port.mk>
