# $OpenBSD$

COMMENT=	Pretty-print tabular data

MODPY_EGG_VERSION=	0.7.7
DISTNAME=		tabulate-${MODPY_EGG_VERSION}
PKGNAME=		py-tabulate-${MODPY_EGG_VERSION}

CATEGORIES=	textproc devel

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_SETUPTOOLS=	Yes

.include <bsd.port.mk>
