     SUBDIR =
     SUBDIR += py-adal
     SUBDIR += py-azure
     SUBDIR += py-azure-batch
     SUBDIR += py-azure-common
     SUBDIR += py-azure-graphrbac
     SUBDIR += py-azure-mgmt
     SUBDIR += py-azure-mgmt-authorization
     SUBDIR += py-azure-mgmt-common
     SUBDIR += py-azure-mgmt-compute
     SUBDIR += py-azure-mgmt-containerregistry
     SUBDIR += py-azure-mgmt-dns
     SUBDIR += py-azure-mgmt-network
     SUBDIR += py-azure-mgmt-nspkg
     SUBDIR += py-azure-mgmt-resource
     SUBDIR += py-azure-mgmt-storage
     SUBDIR += py-azure-mgmt-trafficmanager
     SUBDIR += py-azure-mgmt-web
     SUBDIR += py-azure-nspkg
     SUBDIR += py-azure-servicebus
     SUBDIR += py-azure-servicemanagement-legacy
     SUBDIR += py-azure-storage
     SUBDIR += py-msrest
     SUBDIR += py-msrestazure

.include <bsd.port.subdir.mk>
