# $OpenBSD$

COMMENT=	scandir, a better directory iterator and faster os.walk()

MODPY_EGG_VERSION=	1.5
DISTNAME=		scandir-${MODPY_EGG_VERSION}
PKGNAME=		py-scandir-${MODPY_EGG_VERSION}

HOMEPAGE=		https://github.com/benhoyt/scandir

CATEGORIES=	devel

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_SETUPTOOLS=	Yes

.include <bsd.port.mk>
