# $OpenBSD$

COMMENT=	pure-Python full text indexing, search, and spell checking

MODPY_EGG_VERSION=	2.7.4
DISTNAME=		Whoosh-${MODPY_EGG_VERSION}
PKGNAME=		py-whoosh-${MODPY_EGG_VERSION}

HOMEPAGE=		http://bitbucket.org/mchaput/whoosh

CATEGORIES=	textproc devel

# MIT
PERMIT_PACKAGE_CDROM=	Yes

MODULES=		lang/python

MODPY_PI=		Yes
MODPY_SETUPTOOLS=	Yes

.include <bsd.port.mk>
